// On-page intro text + FAQ for category/brand landing pages — the brief's
// item 7: these pages previously had almost no real text (a filter strip
// and a product grid), which reads as thin content to Google. Keyed by the
// same lowercase category name Shop.jsx's CATEGORY_SEO map uses.
export const CATEGORY_INTRO = {
  display: 'Noyon Telecom imports and stocks mobile phone display assemblies at wholesale prices for repair shops, service centers, and dealers across Bangladesh. Our display range covers OLED, LCD, and Incell panels for popular Samsung, Vivo, Oppo, Xiaomi, and other brand models — each listing states the exact panel type and compatible models so you order the right part the first time. OLED panels generally offer better color and battery efficiency, while LCD and Incell options give a lower-cost alternative for budget repairs; our team can help you choose based on your customer\'s needs and budget over WhatsApp. Every display is pre-tested before dispatch and carries a 7-day testing warranty, so you can confirm functionality before permanent installation. We deliver inside Dhaka within 24-48 hours and nationwide via courier, with bulk pricing available for repair shops ordering multiple units.',
  battery: 'We supply original and high-quality replacement mobile phone batteries at wholesale rates to repair shops and dealers throughout Bangladesh. Battery health is one of the most common repair requests, and using a genuine or reliable third-party cell matters for customer safety and satisfaction — our listings note the battery capacity (mAh) and compatible models for each product. All batteries are pre-tested before shipping and covered by our 7-day testing warranty (note that physical damage or swelling after delivery isn\'t covered, since that reflects installation or usage conditions rather than a manufacturing defect). We stock batteries for Samsung, Vivo, Oppo, Xiaomi, and other major brands sold in Bangladesh, with wholesale pricing that scales for bulk orders — ideal for repair shops that go through batteries regularly.',
  'charging port': 'Charging port failures are among the most frequent repair jobs mobile technicians handle, usually caused by dust buildup, physical wear, or liquid damage. Noyon Telecom stocks wholesale charging port flex cables and sub-boards compatible with a wide range of Samsung, Vivo, Oppo, Xiaomi, and other smartphone models, each listed with its exact compatible models so you can match the right part quickly. A charging port replacement is typically a straightforward repair, but using the correct flex cable variant for the exact model is essential to avoid a poor charging connection. Every charging port we sell is pre-tested before dispatch and comes with a 7-day testing warranty. We deliver across Bangladesh with fast turnaround inside Dhaka, and offer wholesale pricing for repair shops ordering in bulk.',
  'back glass': 'Back glass panels are a common casualty of drops, and replacing a cracked one is one of the more visually impactful repairs a shop can offer. Noyon Telecom imports back glass and body housing parts at wholesale prices for a wide range of smartphone models, with each listing specifying the exact compatible model so you avoid a color or fit mismatch. We also stock camera lens glass and full housing kits for models where the back glass and frame are sold together. All parts are quality-checked before dispatch and backed by our 7-day testing warranty for manufacturing defects. Wholesale pricing applies for bulk orders, and we deliver nationwide across Bangladesh with fast delivery inside Dhaka — ideal for repair shops that need to keep back glass stock on hand for popular models.',
  oled: 'OLED (Organic Light-Emitting Diode) displays offer richer colors, true blacks, and better power efficiency compared to traditional LCD panels, making them the preferred replacement option for flagship and mid-range smartphones. Noyon Telecom stocks wholesale OLED display assemblies, pre-tested before dispatch, for a range of Samsung, Vivo, Oppo, Xiaomi, and other brand models. Each product listing specifies the exact compatible models, since OLED panels are model-specific and not interchangeable across devices. We recommend confirming your exact model via WhatsApp before ordering in bulk to avoid a mismatch. Every OLED display we sell carries a 7-day testing warranty, and we offer wholesale pricing for repair shops and dealers ordering multiple units, with delivery across Bangladesh.',
  lcd: 'LCD (Liquid Crystal Display) panels remain a reliable, cost-effective replacement option for many smartphone models, especially for budget and mid-range devices. Noyon Telecom stocks wholesale LCD display assemblies imported and tested for quality before they reach our warehouse, covering a wide range of Samsung, Vivo, Oppo, Xiaomi, and other brand models. LCD panels are generally more affordable than OLED alternatives, making them a popular choice for repair shops serving price-sensitive customers, while still offering solid display quality for everyday use. Each listing states the exact compatible models — confirm your device\'s exact model via WhatsApp before a bulk order. Every LCD panel carries our 7-day testing warranty, with wholesale pricing and nationwide delivery across Bangladesh.',
  touch: 'A touch screen digitizer registers finger input on a smartphone\'s display and is a separate component from the display panel itself in many repair scenarios, particularly for combo assemblies where the two are fused. Noyon Telecom stocks wholesale touch screen digitizers compatible with a range of Samsung, Vivo, Oppo, Xiaomi, and other smartphone models, with each listing specifying compatible models to help you order the correct part. A malfunctioning touch response, unresponsive areas, or ghost touches are the typical symptoms that call for a digitizer replacement. All touch screen parts are quality-checked before dispatch and covered by our 7-day testing warranty. We offer wholesale pricing for repair shops and dealers, with fast delivery inside Dhaka and nationwide courier service across Bangladesh.',
  housing: 'Housing and body replacement parts let a repair shop restore a smartphone\'s outer frame and structure after drop damage or heavy wear. Noyon Telecom stocks wholesale housing parts for a range of smartphone models, with each listing specifying exact compatible models and finish/color options where applicable. A full housing replacement is often paired with a back glass or middle frame swap depending on the extent of the damage — our team can advise on the right combination for a given repair job over WhatsApp. All housing parts are quality-checked before dispatch and backed by our 7-day testing warranty for manufacturing defects. We offer wholesale pricing for bulk orders and deliver nationwide across Bangladesh, with fast turnaround inside Dhaka.',
  frame: 'The middle frame (chassis) is the structural backbone of a smartphone, holding the display, battery, and other internal components in place. Noyon Telecom stocks wholesale middle frame replacement parts for a range of smartphone models, each listing specifying exact compatible models to ensure a correct fit. A bent or cracked frame from a drop can affect how well other components seat, making a frame replacement necessary for a proper repair rather than a cosmetic one. All frame parts are quality-checked before dispatch and covered by our 7-day testing warranty. We offer wholesale pricing for repair shops and dealers ordering in bulk, with delivery available across Bangladesh and fast turnaround inside Dhaka.',
  camera: 'Camera module failures — blurry photos, a black screen in the camera app, or a cracked lens — are common repair requests, and Noyon Telecom stocks wholesale front and rear camera modules for a range of Samsung, Vivo, Oppo, Xiaomi, and other smartphone models. Each listing specifies the exact compatible models and camera position (front/rear, main/ultra-wide/macro where applicable), so you can order the precise part your repair needs. Camera modules are pre-tested before dispatch to confirm they function correctly, and every purchase carries our 7-day testing warranty. We offer wholesale pricing for repair shops and technicians ordering multiple units, with fast delivery inside Dhaka and nationwide courier service across Bangladesh.',
  speaker: 'Loudspeaker and ringer issues — no sound, distorted audio, or a rattling noise — are a common and usually quick repair. Noyon Telecom stocks wholesale speaker replacement parts for a range of smartphone models, with each listing specifying exact compatible models. Speaker modules are quality-checked before dispatch to confirm sound output before they reach you, and every purchase carries our 7-day testing warranty. We supply repair shops and technicians across Bangladesh with wholesale pricing on bulk orders, and offer fast delivery inside Dhaka along with nationwide courier service for shops outside the capital.',
  microphone: 'Microphone problems — the other party can\'t hear you clearly during calls, or voice recordings sound muffled — usually point to a faulty mic component rather than a software issue. Noyon Telecom stocks wholesale microphone replacement parts for a range of smartphone models, with each listing specifying exact compatible models. All microphone parts are quality-checked before dispatch and backed by our 7-day testing warranty. We serve repair shops, technicians, and service centers across Bangladesh with wholesale pricing and reliable delivery, including fast turnaround inside Dhaka.',
  flex: 'Flex cables and ribbon connectors link various components inside a smartphone — buttons, sensors, cameras, and more — and a damaged or worn flex cable can cause a range of intermittent issues. Noyon Telecom stocks wholesale flex cables for a range of smartphone models and functions, with each listing specifying the exact compatible model and function to help you identify the correct part for your repair. All flex cables are quality-checked before dispatch and carry our 7-day testing warranty. We offer wholesale pricing for repair shops and technicians across Bangladesh, with fast delivery inside Dhaka and nationwide courier service.',
  'logic board': 'Logic board and small board repairs are more advanced work, often required when a device won\'t power on, has charging IC failure, or shows other deeper hardware faults. Noyon Telecom stocks wholesale logic board and small board replacement parts for a range of smartphone models, with each listing specifying exact compatible models. These parts are best suited for experienced technicians comfortable with board-level repair. All logic boards are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and service centers across Bangladesh with wholesale pricing and reliable nationwide delivery.',
  motherboard: 'A motherboard (mainboard) replacement is typically needed when a smartphone has suffered severe liquid damage, a major short circuit, or other faults beyond component-level repair. Noyon Telecom stocks wholesale motherboard replacement parts for a range of smartphone models, with each listing specifying exact compatible models. This is advanced repair work best handled by experienced technicians. All motherboards are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and service centers across Bangladesh with wholesale pricing and reliable nationwide delivery.',
  ic: 'Power ICs, charging ICs, and other repair chips are used by technicians to fix specific hardware faults at the component level — a charging IC failure, for instance, can cause a device to not charge even with a working charging port and cable. Noyon Telecom stocks wholesale IC chips for smartphone repair, with each listing specifying the exact chip type and compatible models. This is specialized repair work best suited to experienced technicians with micro-soldering equipment. All ICs are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and technicians across Bangladesh with wholesale pricing and reliable delivery.',
  cpu: 'CPU (processor) replacement is advanced, specialized repair work typically undertaken when a device has suffered a processor-level fault, and requires micro-soldering expertise. Noyon Telecom stocks wholesale CPU replacement chips for smartphone repair, with each listing specifying the exact chip and compatible models. All CPU chips are quality-checked before dispatch and carry our 7-day testing warranty. We supply experienced technicians and service centers across Bangladesh with wholesale pricing and reliable nationwide delivery.',
  buttons: 'Power, volume, and home button failures are common wear-and-tear issues, especially on older or heavily-used devices. Noyon Telecom stocks wholesale button and switch replacement parts for a range of smartphone models, with each listing specifying exact compatible models. All button parts are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and technicians across Bangladesh with wholesale pricing on bulk orders, with fast delivery inside Dhaka and nationwide courier service.',
  'sim tray': 'A SIM card tray can get lost, bent, or its ejector mechanism can fail over time, and Noyon Telecom stocks wholesale SIM tray replacement parts for a range of smartphone models, colors, and single/dual-SIM variants. Each listing specifies exact compatible models and tray type to help you order the correct part. All SIM trays are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and dealers across Bangladesh with wholesale pricing and reliable delivery, including fast turnaround inside Dhaka.',
  fingerprint: 'Fingerprint sensor issues — slow recognition, failure to register a fingerprint, or a sensor that stops working entirely — are a common repair request on devices with a physical or in-display fingerprint sensor. Noyon Telecom stocks wholesale fingerprint sensor replacement parts for a range of smartphone models, with each listing specifying exact compatible models. All fingerprint sensors are quality-checked before dispatch and carry our 7-day testing warranty. We supply repair shops and technicians across Bangladesh with wholesale pricing and reliable delivery.',
  'face id': 'Face ID / dot projector module failures affect facial recognition unlock on supported devices, and are a more specialized repair than most touch/display work. Noyon Telecom stocks wholesale Face ID module replacement parts for supported smartphone models, with each listing specifying exact compatible models. This repair typically requires careful handling of calibration data — our team can advise over WhatsApp. All modules are quality-checked before dispatch and carry our 7-day testing warranty. We supply experienced repair shops and technicians across Bangladesh with wholesale pricing and reliable delivery.',
  'repair tools': 'Beyond replacement parts, Noyon Telecom also stocks wholesale mobile phone repair tools and equipment for technicians and repair shops across Bangladesh — the everyday essentials that keep a repair bench running smoothly. Each listing specifies the tool type and any relevant specifications. All tools are quality-checked before dispatch, and we offer wholesale pricing for shops equipping a new bench or restocking consumables, with reliable delivery nationwide.',
  accessories: 'Alongside spare parts, Noyon Telecom stocks wholesale mobile phone accessories for dealers and shops across Bangladesh, at competitive rates suited to resale. Each listing specifies the exact product and compatible models where relevant. We offer wholesale pricing for bulk orders and reliable delivery nationwide, with fast turnaround inside Dhaka — a convenient one-stop order alongside your spare parts purchase.',
};

// Reusable across every category/brand page rather than 43 hand-written
// FAQ sets — the intro text above is what varies per page; these questions
// are genuinely the same across every part type/brand. `subject` is the
// category or brand name, substituted into the first question.
export function buildCategoryFaq(subject) {
  return [
    {
      q: `Is this ${subject} compatible with my exact phone model?`,
      a: 'Compatibility varies by product — check the compatible models list on each product page, or message us on WhatsApp with your exact model to confirm before ordering, especially for bulk orders.',
    },
    {
      q: 'What is the minimum order quantity (MOQ)?',
      a: 'MOQ varies by product and is shown on every product page. Many accessories and small parts have an MOQ of 5-10 units; larger components like displays are often MOQ 1.',
    },
    {
      q: 'Do these parts come with a warranty?',
      a: 'Yes, every part carries a 7-day testing warranty from the delivery date, covering manufacturing defects and dead-on-arrival items.',
    },
    {
      q: 'Do you deliver outside Dhaka?',
      a: 'Yes, we deliver nationwide across Bangladesh via courier, typically within 2-4 business days, alongside 24-48 hour delivery inside Dhaka.',
    },
  ];
}

// Brand pages don't have a hand-written intro per brand (20 brands would be
// a lot of near-duplicate text without real per-brand detail to add) — this
// template still produces a genuine, non-generic paragraph since the brand
// name and category list are substituted in from real, live catalog data.
export function buildBrandIntro(brand, activeCategories) {
  const categoryList = activeCategories.length ? activeCategories.join(', ') : 'displays, batteries, charging ports, and back glass';
  return `Noyon Telecom is a wholesale importer and distributor of ${brand} mobile phone spare parts in Bangladesh, supplying repair shops, service centers, and dealers with genuine and high-quality replacement components. Our current ${brand} stock covers ${categoryList}, with each product listing its exact compatible model so you can order the right part with confidence. Every part is pre-tested before dispatch and carries a 7-day testing warranty. We offer wholesale and bulk pricing for repair shops and dealers, with fast delivery inside Dhaka and nationwide courier service across Bangladesh. Browse the ${brand} parts below, or message us on WhatsApp with your exact model if you don't see what you need.`;
}
